### ISSUE TITLE
record cursor by mouse 

### ISSUE THREAD

**Issue by ghost** [akaalias/obsidian-remember-cursor#1]
open issue for record.

in v0.0.4 version.

ob version: v0.11.3 

Steps: 
1. move cursor by keyboard 
2. close page and reopen, check the cursor  ---- result is right cursor position. 
3. move cursor by mouse 
4. close page by mouse
5. reopen that page,
6. check the cursor position  ---- the cursor position is previous cursor position by keyboard. 

Thank you will fix.

**Comment by akaalias** [comment]
Thanks! Closing issue since mouse clicks now work as of release 0.0.5

**Comment by ghost** [comment]
Please upload "main.js" file. I can't find Community plugins " in obsidian. 
Thank you .
